% define a weighted adjacency matrix
adjacency_matrix = [...
    0, .1, 0, 0, 0;...
    .1, 0, .5, 0, 0;...
    0, .5, 0, 1, 0;...
    0, 0, 1, 0, 2;...
    0, 0, 0, 2, 0;...
];

% call webweb
webweb(adjacency_matrix);

% [OPTIONAL] set webweb's display default: show weighted edges.

% DBL TODO